import { ComponentStory, ComponentMeta } from '@storybook/react';
declare const HomeStory: ComponentMeta<({ defaultStep, handleSubmit, isBranding, stepResponse, shopTypes, selectedMerchantType, stateTypes, handleStepCallBack, userData, stepsData, theme }: {
    defaultStep: string;
    handleSubmit: (data: any) => void;
    developerKey?: string | undefined;
    secretKey?: string | undefined;
    isBranding?: boolean | undefined;
    stepResponse?: any;
    selectedMerchantType?: any;
    shopTypes?: any[] | undefined;
    stateTypes?: any[] | undefined;
    handleStepCallBack?: any;
    userData: any;
    stepsData: import("../utils/data/stepsData").StepDataType[];
    theme?: Record<string, string> | undefined;
}) => JSX.Element>;
export default HomeStory;
export declare const homepage: ComponentStory<({ defaultStep, handleSubmit, isBranding, stepResponse, shopTypes, selectedMerchantType, stateTypes, handleStepCallBack, userData, stepsData, theme }: {
    defaultStep: string;
    handleSubmit: (data: any) => void;
    developerKey?: string | undefined;
    secretKey?: string | undefined;
    isBranding?: boolean | undefined;
    stepResponse?: any;
    selectedMerchantType?: any;
    shopTypes?: any[] | undefined;
    stateTypes?: any[] | undefined;
    handleStepCallBack?: any;
    userData: any;
    stepsData: import("../utils/data/stepsData").StepDataType[];
    theme?: Record<string, string> | undefined;
}) => JSX.Element>;
